### ISSUE TITLE
'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by DelazJ** [rduivenvoorde/nominatim_locator_filter#1]
Hi Richard,
Typing in the locator search bar `osm Beaucouzé ` pops up the python error dialog below

![nominatim](https://user-images.githubusercontent.com/7983394/46798860-6aa55580-cd53-11e8-9b0e-2e84ba30d201.png)

The town is however found, though clicking on the result does not seem to zoom to it.
Regards.

**Comment by rduivenvoorde** [comment]
@DelazJ hi, what is your setup to have such a nice error messages? Do you have Martin's debug plugin enabled or so?
Anyway: I've seen the here too, and will just remove the debug message, as apparently not reply's have a self.reply ...?

**Comment by rduivenvoorde** [comment]
Also as of the new version 0.2.3 the plugin does not zoom to the 'type' of the result, but just to the given boundingbox (which is better most of the time). So I think Beaucouzé has better results now.

**Comment by rduivenvoorde** [comment]
0.2.3 is release now. Closing this one.
