### ISSUE TITLE
Add note about native support for this feature in 3.20

### ISSUE THREAD

**Issue by kannes** [rduivenvoorde/nominatim_locator_filter#11]
Since 3.20 QGIS has native support for this functionality by using the ">" prefix in the locator bar: https://www.qgis.org/en/site/forusers/visualchangelog320/index.html#feature-nominatim-geocoder-integration

It would be great if you could make a note about this in the README.

Thank you! :))

**Comment by rduivenvoorde** [comment]
Sorry for the late reply, I thought nobody was using this anymore, but recently people asked me to add some stuff.

So: I've added this note, both to README.md and to metadata.txt in 0.3.2)

**Comment by kannes** [comment]
Thank you! <3
