### ISSUE TITLE
sip.enumtype object 'GeometryType' has no member 'Polygon'

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/nominatim_locator_filter#13]
@cxcandid after pulling the PR I get this message when starting QGIS 3.28 with the locator:

![image](https://github.com/rduivenvoorde/nominatim_locator_filter/assets/731673/23862d5e-c844-4c5c-9704-571aa4f9af03)

Probably the typing stuff has changed, but 3.28 did not have QgsWkbTypes.GeometryType.Polygon yet.

Can you please have a look?

**Comment by cxcandid** [comment]
@rduivenvoorde sorry, my fault... I didn't test with the stable QGIS version 3.28. Thanks for the reminder!
I'm trying to make the code compatible.

**Comment by rduivenvoorde** [comment]
Version 0.3.1? @cxcandid the earlier Pull Request is already merged. Can you please create a new one, based on the master version? TIA

**Comment by cxcandid** [comment]
@rduivenvoorde I have created the new request. You can close the issue.
