### ISSUE TITLE
Locator does not zoom properly to some locations

### ISSUE THREAD

**Issue by dbobak** [rduivenvoorde/nominatim_locator_filter#2]
For example, try to find "jegłowa" (it's a village in a south-western Poland). Locator finds the plase, but doble click zooms map out to the 1:4000000 scale. When using OSM place search plugin, zooming works perfectly.

QIGS 3.2.3 on Windows 10 Pro.

**Comment by rduivenvoorde** [comment]
Ok, version 3.2.3 does now zoom to bbox. Closing this issue. Thanks for your comments.
