### ISSUE TITLE
Review setting to force auto complete search

### ISSUE THREAD

**Issue by palmerj** [rduivenvoorde/nominatim_locator_filter#5]
At the moment a space character seems to be needed to force a server query. Maybe make a search after x amount of entered characters?

**Comment by kannes** [comment]
The plugin description mentions the terms of usage for Nominatim: 

> Because it is *NOT* allowed to use the Nominatim service as a 'search as you type' service,
> the locator will not fire a request unless you end your string with a space or enter.

**Comment by rduivenvoorde** [comment]
Yeah, that is deliberately.
